# This file was generated by GoReleaser. DO NOT EDIT.
cask "cfgctl" do
  name "cfgctl"
  desc "CLI for managing complex configuration setup"
  homepage "https://github.com/jmreicha/cfgctl"
  version "0.4.9"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cfgctl"

  on_macos do
    on_intel do
      url "https://github.com/jmreicha/cfgctl/releases/download/v#{version}/cfgctl_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/jmreicha/cfgctl"
      sha256 "936e0465089adfb808f5ecb56e4a5dd3828ba0dd18ae6050db83c1cce235c8c8"
    end
    on_arm do
      url "https://github.com/jmreicha/cfgctl/releases/download/v#{version}/cfgctl_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/jmreicha/cfgctl"
      sha256 "e9b74a74f6e57d1a836dafcf86c63f6711a81f2e7530fdc7d7a3159ad9a0515a"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/jmreicha/cfgctl/releases/download/v#{version}/cfgctl_#{version}_linux_amd64.tar.gz",
        verified: "github.com/jmreicha/cfgctl"
      sha256 "e9f1b03d36ec1f3272ae3e2b6cc47ba19f97103149ecabaff896fb667b8bfd77"
    end
    on_arm do
      url "https://github.com/jmreicha/cfgctl/releases/download/v#{version}/cfgctl_#{version}_linux_arm64.tar.gz",
        verified: "github.com/jmreicha/cfgctl"
      sha256 "9c405c005d96ff2306425287e17e974dda9e2b343ee04af127b7ed42523847b8"
    end
  end

  # No zap stanza required
end
