# This file was generated by GoReleaser. DO NOT EDIT.
cask "cfgctl" do
  name "cfgctl"
  desc "CLI for managing complex configuration setup"
  homepage "https://github.com/jmreicha/cfgctl"
  version "0.8.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cfgctl"

  on_macos do
    on_intel do
      url "https://github.com/jmreicha/cfgctl/releases/download/v#{version}/cfgctl_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/jmreicha/cfgctl"
      sha256 "ae75e3743cb06d3253010659a9b2543b683f2b4c5494eca46f9453d7e4e85669"
    end
    on_arm do
      url "https://github.com/jmreicha/cfgctl/releases/download/v#{version}/cfgctl_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/jmreicha/cfgctl"
      sha256 "e6dd0ba621931ea15bf64bdf17b020a9a3e23dc44bed162baf3a8fd79965db8e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/jmreicha/cfgctl/releases/download/v#{version}/cfgctl_#{version}_linux_amd64.tar.gz",
        verified: "github.com/jmreicha/cfgctl"
      sha256 "8f160bf33096492b644183215c768e2bf9d9cc25be79cc13b15f1db8bd3467a8"
    end
    on_arm do
      url "https://github.com/jmreicha/cfgctl/releases/download/v#{version}/cfgctl_#{version}_linux_arm64.tar.gz",
        verified: "github.com/jmreicha/cfgctl"
      sha256 "f227a1e328c95c0222573d4cae7f650981d4780be61b6aa5ddb246c22d378a21"
    end
  end

  # No zap stanza required
end
