# This file was generated by GoReleaser. DO NOT EDIT.
cask "cfgctl" do
  name "cfgctl"
  desc "CLI for managing complex configuration setup"
  homepage "https://github.com/jmreicha/cfgctl"
  version "0.7.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cfgctl"

  on_macos do
    on_intel do
      url "https://github.com/jmreicha/cfgctl/releases/download/v#{version}/cfgctl_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/jmreicha/cfgctl"
      sha256 "ca0cc5ac9c7da7557367ecbb69e47f5b057e0d71b34ab8450feeb3100294034f"
    end
    on_arm do
      url "https://github.com/jmreicha/cfgctl/releases/download/v#{version}/cfgctl_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/jmreicha/cfgctl"
      sha256 "f1d316f9c91f2d3e2a430d951e69ceee46e23465b6d2c31064ce7ae59a794226"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/jmreicha/cfgctl/releases/download/v#{version}/cfgctl_#{version}_linux_amd64.tar.gz",
        verified: "github.com/jmreicha/cfgctl"
      sha256 "7473e5d4d5c4556a15320bdb231f2a81f375ed4c82885c18da3237045b951c01"
    end
    on_arm do
      url "https://github.com/jmreicha/cfgctl/releases/download/v#{version}/cfgctl_#{version}_linux_arm64.tar.gz",
        verified: "github.com/jmreicha/cfgctl"
      sha256 "b7478d097db87bdf0226341e6835cd65a3fae1572d58564560a1f70b0f5e4818"
    end
  end

  # No zap stanza required
end
