# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cfgctl < Formula
  desc "CLI for managing complex configuration setup"
  homepage "https://github.com/jmreicha/cfgctl"
  version "0.10.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jmreicha/cfgctl/releases/download/v0.10.0/cfgctl_0.10.0_darwin_amd64.tar.gz"
      sha256 "44b00cf5a20a129c04007065fb5cacefd35cb96064e522cd993db63ea9c34532"

      define_method(:install) do
        bin.install "cfgctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jmreicha/cfgctl/releases/download/v0.10.0/cfgctl_0.10.0_darwin_arm64.tar.gz"
      sha256 "938802de7f33d5f954df65cd0937377229c2c7e12e485b8c4cc9d3eb910e8308"

      define_method(:install) do
        bin.install "cfgctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jmreicha/cfgctl/releases/download/v0.10.0/cfgctl_0.10.0_linux_amd64.tar.gz"
      sha256 "302a424d00b77a3afaa9065caa189fb6e3eb59cb0ffc067a6def1785b2dc1e42"
      define_method(:install) do
        bin.install "cfgctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jmreicha/cfgctl/releases/download/v0.10.0/cfgctl_0.10.0_linux_arm64.tar.gz"
      sha256 "18bf22f861a88f22e5da2a16efe3acc11e10f8040e54e5798093f01fd612ce12"
      define_method(:install) do
        bin.install "cfgctl"
      end
    end
  end
end
